### ISSUE TITLE
[Question/Feature Request] Displaying romaji instead of kanji 

### ISSUE THREAD

**Issue by Zenrac** [enricobacis/lyricwikia#3]
Hi, i'm using your API and it is quite good! 
The only point that is missing is a parameter to display the romaji lyrics instead of the kanji lyrics. (for japanese song for example)

How can I do that ? 

(Example : http://lyrics.wikia.com/wiki/The_GazettE:%E8%B5%A4%E3%81%84%E3%83%AF%E3%83%B3%E3%83%94%E3%83%BC%E3%82%B9 first there are the kanji lyrics, and below, the romaji lyrics)

**Comment by enricobacis** [comment]
Interesting that they have two lyricbox in the page. An idea could be to return a tuple in case of multiple lyricbox, but I don't want to do that because it will break the usage of people already using it.

Another idea would be to have another API such as get_all_lyrics that always return a tuple of the lyrics and then you can use the second one. That's because there might be other languages with multiple representations, and I'd like not to have a switch for all of them, it should be one layer above lyricwikia.

Would that be ok?
